"""chunks table for gold-layer chunking

Revision ID: 6ca5ca7f71c4
Revises: 4022a38c1042
Create Date: 2026-07-18 16:37:41.864954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca5ca7f71c4'
down_revision: Union[str, Sequence[str], None] = '4022a38c1042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('qdrant_point_id', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'seq', name='uq_chunks_filing_id_seq')
    )
    op.create_index(op.f('ix_chunks_filing_id'), 'chunks', ['filing_id'], unique=False)
    op.create_index(op.f('ix_chunks_text_hash'), 'chunks', ['text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_text_hash'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_filing_id'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
